
FROM 089465505731.dkr.ecr.ap-southeast-1.amazonaws.com/dotnet8:sdk as agent
ARG DEBIAN_FRONTEND=noninteractive
ARG TRACER_VERSION
ARG BUILDARCH
COPY ./*.sh /app
RUN /app/${TARGETARCH}.sh
ARG tag=NA
ENV IMAGE_TAG=${tag}

ARG asmver=1.0.0.0
ENV ASSEMBLY_VERSION=${asmver}
FROM agent as base
WORKDIR /app
EXPOSE 5000
ENV DEBIAN_FRONTEND noninteractive
RUN uname -m

FROM base AS build

WORKDIR /src
COPY . .
RUN echo ls -la ./

RUN dotnet restore "src/Conduit/Conduit.csproj"
RUN dotnet build "src/Conduit/Conduit.csproj" -c Release -o /app/build
FROM build AS publish
ARG asmver
RUN dotnet publish -c Release -o /app/publish -p:UseAppHost=false

FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .
ENTRYPOINT ["dotnet", "Conduit.dll"]