---
apiVersion: v1
kind: Pod
spec:
  serviceAccountName: jenkins-agent
  automountServiceAccountToken: true
  containers:
  - name: jnlp
    image: 670440716409.dkr.ecr.ap-southeast-1.amazonaws.com/jenkins-buildah-multiarch:ubuntu-noble-20240530
    imagePullPolicy: Always
    # resources:
    #    limits:
    #       memory: "4096Mi"
    #       cpu: "2000m"
    #    requests:
    #       memory: "2048Mi"
    #       cpu: "1000m"
    securityContext:
      privileged: true
    env :
    - name: JENKINS_SCM_SSH
      valueFrom:
        secretKeyRef:
          name: jenkins-scm-ssh
          key: jenkins-scm-ssh
    workingDir: /home/jenkins/agent
    volumeMounts:
      - mountPath: /home/jenkins/agent
        name: workspace-volume
    terminationMessagePolicy: FallbackToLogsOnError
    hostNetwork: false
    enableServiceLinks: false
    dnsPolicy: Default
    terminationGracePeriodSeconds: 30
  volumes:
    - name: workspace-volume
      emptyDir: {}
  nodeSelector:
    kubernetes.io/os: linux
    # kubernetes.io/arch: amd64
    node.kubernetes.io/prod-jenkins-cluster-ng-minimum-linux-emvacs: ""
  tolerations: 
    - key: "emvacspod"
      operator: "Equal"
      value: "true"
      effect: "NoExecute"